regsvr32.exe /u "%~dp0explorerdataprovider.dll"
del "c:\windows\BioControls.dll"
del "c:\windows\Dialog.dll"
del "c:\windows\Dialog.dll.config"
del "c:\windows\Dialog.dll.reg"
del "c:\windows\IMPlugin.dll"
del "c:\windows\log4net.dll"
del "c:\windows\Mocker.exe"
del "c:\windows\PluginManager.dll"
del "c:\windows\SecuBSPMx.NET.dll"
del "c:\windows\SecuGen.FDxSDKPro.Windows.dll"
del "c:\windows\Plugins\DP.dll"
del "c:\windows\Plugins\SG.dll"
del "c:\windows\Plugins\IB.dll"
del "c:\windows\System32\IdentaZoneAP.dll"

pause 