//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentaZone.Indss.MatchingService.MatchingServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="IdentaZone.Indss", ConfigurationName="MatchingServiceReference.IMatchingService")]
    public interface IMatchingService {
        
        // CODEGEN: Generating message contract since the operation Echo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="IdentaZone.Indss/IMatchingService/Echo", ReplyAction="IdentaZone.Indss/IMatchingService/EchoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IdentaZone.Indss.MatchingService.MatchingServiceReference.EchoResponse Echo(IdentaZone.Indss.MatchingService.MatchingServiceReference.EchoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="IdentaZone.Indss/IMatchingService/Echo", ReplyAction="IdentaZone.Indss/IMatchingService/EchoResponse")]
        System.Threading.Tasks.Task<IdentaZone.Indss.MatchingService.MatchingServiceReference.EchoResponse> EchoAsync(IdentaZone.Indss.MatchingService.MatchingServiceReference.EchoRequest request);
        
        // CODEGEN: Generating message contract since the operation Match is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="IdentaZone.Indss/IMatchingService/Match", ReplyAction="IdentaZone.Indss/IMatchingService/MatchResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IdentaZone.Indss.MatchingService.MatchingServiceReference.MatchResponse Match(IdentaZone.Indss.MatchingService.MatchingServiceReference.MatchRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="IdentaZone.Indss/IMatchingService/Match", ReplyAction="IdentaZone.Indss/IMatchingService/MatchResponse")]
        System.Threading.Tasks.Task<IdentaZone.Indss.MatchingService.MatchingServiceReference.MatchResponse> MatchAsync(IdentaZone.Indss.MatchingService.MatchingServiceReference.MatchRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetBspProvidersList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="IdentaZone.Indss/IMatchingService/GetBspProvidersList", ReplyAction="IdentaZone.Indss/IMatchingService/GetBspProvidersListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IdentaZone.Indss.MatchingService.MatchingServiceReference.GetBspProvidersListResponse GetBspProvidersList(IdentaZone.Indss.MatchingService.MatchingServiceReference.GetBspProvidersListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="IdentaZone.Indss/IMatchingService/GetBspProvidersList", ReplyAction="IdentaZone.Indss/IMatchingService/GetBspProvidersListResponse")]
        System.Threading.Tasks.Task<IdentaZone.Indss.MatchingService.MatchingServiceReference.GetBspProvidersListResponse> GetBspProvidersListAsync(IdentaZone.Indss.MatchingService.MatchingServiceReference.GetBspProvidersListRequest request);
        
        // CODEGEN: Generating message contract since the operation AddBspTemplate is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="IdentaZone.Indss/IMatchingService/AddBspTemplate", ReplyAction="IdentaZone.Indss/IMatchingService/AddBspTemplateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IdentaZone.Indss.MatchingService.MatchingServiceReference.AddBspTemplateResponse AddBspTemplate(IdentaZone.Indss.MatchingService.MatchingServiceReference.AddBspTemplateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="IdentaZone.Indss/IMatchingService/AddBspTemplate", ReplyAction="IdentaZone.Indss/IMatchingService/AddBspTemplateResponse")]
        System.Threading.Tasks.Task<IdentaZone.Indss.MatchingService.MatchingServiceReference.AddBspTemplateResponse> AddBspTemplateAsync(IdentaZone.Indss.MatchingService.MatchingServiceReference.AddBspTemplateRequest request);
        
        // CODEGEN: Generating message contract since the operation EnableUser is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="IdentaZone.Indss/IMatchingService/EnableUser", ReplyAction="IdentaZone.Indss/IMatchingService/EnableUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IdentaZone.Indss.MatchingService.MatchingServiceReference.EnableUserResponse EnableUser(IdentaZone.Indss.MatchingService.MatchingServiceReference.EnableUserRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="IdentaZone.Indss/IMatchingService/EnableUser", ReplyAction="IdentaZone.Indss/IMatchingService/EnableUserResponse")]
        System.Threading.Tasks.Task<IdentaZone.Indss.MatchingService.MatchingServiceReference.EnableUserResponse> EnableUserAsync(IdentaZone.Indss.MatchingService.MatchingServiceReference.EnableUserRequest1 request);
        
        // CODEGEN: Generating message contract since the operation ConnectDB is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="IdentaZone.Indss/IMatchingService/ConnectDB", ReplyAction="IdentaZone.Indss/IMatchingService/ConnectDBResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IdentaZone.Indss.MatchingService.MatchingServiceReference.ConnectDBResponse ConnectDB(IdentaZone.Indss.MatchingService.MatchingServiceReference.ConnectDBRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="IdentaZone.Indss/IMatchingService/ConnectDB", ReplyAction="IdentaZone.Indss/IMatchingService/ConnectDBResponse")]
        System.Threading.Tasks.Task<IdentaZone.Indss.MatchingService.MatchingServiceReference.ConnectDBResponse> ConnectDBAsync(IdentaZone.Indss.MatchingService.MatchingServiceReference.ConnectDBRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EchoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="echoRequest", Namespace="IdentaZone.Indss", Order=0)]
        public string echoRequest1;
        
        public EchoRequest() {
        }
        
        public EchoRequest(string echoRequest1) {
            this.echoRequest1 = echoRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EchoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IdentaZone.Indss", Order=0)]
        public string Response;
        
        public EchoResponse() {
        }
        
        public EchoResponse(string Response) {
            this.Response = Response;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="IdentaZone.Indss")]
    public partial class matchRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pinField;
        
        private int bsp_CodeField;
        
        private string loginNameField;
        
        private byte[] templateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Pin {
            get {
                return this.pinField;
            }
            set {
                this.pinField = value;
                this.RaisePropertyChanged("Pin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Bsp_Code {
            get {
                return this.bsp_CodeField;
            }
            set {
                this.bsp_CodeField = value;
                this.RaisePropertyChanged("Bsp_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LoginName {
            get {
                return this.loginNameField;
            }
            set {
                this.loginNameField = value;
                this.RaisePropertyChanged("LoginName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=3)]
        public byte[] Template {
            get {
                return this.templateField;
            }
            set {
                this.templateField = value;
                this.RaisePropertyChanged("Template");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MatchRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IdentaZone.Indss", Order=0)]
        public IdentaZone.Indss.MatchingService.MatchingServiceReference.matchRequest matchRequest;
        
        public MatchRequest1() {
        }
        
        public MatchRequest1(IdentaZone.Indss.MatchingService.MatchingServiceReference.matchRequest matchRequest) {
            this.matchRequest = matchRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MatchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IdentaZone.Indss", Order=0)]
        public string Response;
        
        public MatchResponse() {
        }
        
        public MatchResponse(string Response) {
            this.Response = Response;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="IdentaZone.Indss")]
    public partial class Empty : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBspProvidersListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IdentaZone.Indss", Order=0)]
        public IdentaZone.Indss.MatchingService.MatchingServiceReference.Empty Empty;
        
        public GetBspProvidersListRequest() {
        }
        
        public GetBspProvidersListRequest(IdentaZone.Indss.MatchingService.MatchingServiceReference.Empty Empty) {
            this.Empty = Empty;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBspProvidersListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IdentaZone.Indss", Order=0)]
        public string Response;
        
        public GetBspProvidersListResponse() {
        }
        
        public GetBspProvidersListResponse(string Response) {
            this.Response = Response;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="IdentaZone.Indss")]
    public partial class AddTemplateRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pinField;
        
        private string loginNameField;
        
        private int sysRoleField;
        
        private int bspTypeField;
        
        private int bspModeField;
        
        private byte[] bspTemplateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Pin {
            get {
                return this.pinField;
            }
            set {
                this.pinField = value;
                this.RaisePropertyChanged("Pin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LoginName {
            get {
                return this.loginNameField;
            }
            set {
                this.loginNameField = value;
                this.RaisePropertyChanged("LoginName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int SysRole {
            get {
                return this.sysRoleField;
            }
            set {
                this.sysRoleField = value;
                this.RaisePropertyChanged("SysRole");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int BspType {
            get {
                return this.bspTypeField;
            }
            set {
                this.bspTypeField = value;
                this.RaisePropertyChanged("BspType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int BspMode {
            get {
                return this.bspModeField;
            }
            set {
                this.bspModeField = value;
                this.RaisePropertyChanged("BspMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=5)]
        public byte[] BspTemplate {
            get {
                return this.bspTemplateField;
            }
            set {
                this.bspTemplateField = value;
                this.RaisePropertyChanged("BspTemplate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBspTemplateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IdentaZone.Indss", Order=0)]
        public IdentaZone.Indss.MatchingService.MatchingServiceReference.AddTemplateRequest AddTemplateRequest;
        
        public AddBspTemplateRequest() {
        }
        
        public AddBspTemplateRequest(IdentaZone.Indss.MatchingService.MatchingServiceReference.AddTemplateRequest AddTemplateRequest) {
            this.AddTemplateRequest = AddTemplateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBspTemplateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IdentaZone.Indss", Order=0)]
        public string Response;
        
        public AddBspTemplateResponse() {
        }
        
        public AddBspTemplateResponse(string Response) {
            this.Response = Response;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="IdentaZone.Indss")]
    public partial class enableUserRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pinField;
        
        private bool accFlagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Pin {
            get {
                return this.pinField;
            }
            set {
                this.pinField = value;
                this.RaisePropertyChanged("Pin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool AccFlag {
            get {
                return this.accFlagField;
            }
            set {
                this.accFlagField = value;
                this.RaisePropertyChanged("AccFlag");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnableUserRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IdentaZone.Indss", Order=0)]
        public IdentaZone.Indss.MatchingService.MatchingServiceReference.enableUserRequest enableUserRequest;
        
        public EnableUserRequest1() {
        }
        
        public EnableUserRequest1(IdentaZone.Indss.MatchingService.MatchingServiceReference.enableUserRequest enableUserRequest) {
            this.enableUserRequest = enableUserRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnableUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IdentaZone.Indss", Order=0)]
        public string Response;
        
        public EnableUserResponse() {
        }
        
        public EnableUserResponse(string Response) {
            this.Response = Response;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="IdentaZone.Indss")]
    public partial class connectDBRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serverField;
        
        private string portField;
        
        private string databaseField;
        
        private string uidField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Server {
            get {
                return this.serverField;
            }
            set {
                this.serverField = value;
                this.RaisePropertyChanged("Server");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
                this.RaisePropertyChanged("Port");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Database {
            get {
                return this.databaseField;
            }
            set {
                this.databaseField = value;
                this.RaisePropertyChanged("Database");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
                this.RaisePropertyChanged("Uid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConnectDBRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IdentaZone.Indss", Order=0)]
        public IdentaZone.Indss.MatchingService.MatchingServiceReference.connectDBRequest connectDBRequest;
        
        public ConnectDBRequest1() {
        }
        
        public ConnectDBRequest1(IdentaZone.Indss.MatchingService.MatchingServiceReference.connectDBRequest connectDBRequest) {
            this.connectDBRequest = connectDBRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConnectDBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IdentaZone.Indss", Order=0)]
        public string Response;
        
        public ConnectDBResponse() {
        }
        
        public ConnectDBResponse(string Response) {
            this.Response = Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchingServiceChannel : IdentaZone.Indss.MatchingService.MatchingServiceReference.IMatchingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatchingServiceClient : System.ServiceModel.ClientBase<IdentaZone.Indss.MatchingService.MatchingServiceReference.IMatchingService>, IdentaZone.Indss.MatchingService.MatchingServiceReference.IMatchingService {
        
        public MatchingServiceClient() {
        }
        
        public MatchingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MatchingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatchingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatchingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IdentaZone.Indss.MatchingService.MatchingServiceReference.EchoResponse IdentaZone.Indss.MatchingService.MatchingServiceReference.IMatchingService.Echo(IdentaZone.Indss.MatchingService.MatchingServiceReference.EchoRequest request) {
            return base.Channel.Echo(request);
        }
        
        public string Echo(string echoRequest1) {
            IdentaZone.Indss.MatchingService.MatchingServiceReference.EchoRequest inValue = new IdentaZone.Indss.MatchingService.MatchingServiceReference.EchoRequest();
            inValue.echoRequest1 = echoRequest1;
            IdentaZone.Indss.MatchingService.MatchingServiceReference.EchoResponse retVal = ((IdentaZone.Indss.MatchingService.MatchingServiceReference.IMatchingService)(this)).Echo(inValue);
            return retVal.Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IdentaZone.Indss.MatchingService.MatchingServiceReference.EchoResponse> IdentaZone.Indss.MatchingService.MatchingServiceReference.IMatchingService.EchoAsync(IdentaZone.Indss.MatchingService.MatchingServiceReference.EchoRequest request) {
            return base.Channel.EchoAsync(request);
        }
        
        public System.Threading.Tasks.Task<IdentaZone.Indss.MatchingService.MatchingServiceReference.EchoResponse> EchoAsync(string echoRequest1) {
            IdentaZone.Indss.MatchingService.MatchingServiceReference.EchoRequest inValue = new IdentaZone.Indss.MatchingService.MatchingServiceReference.EchoRequest();
            inValue.echoRequest1 = echoRequest1;
            return ((IdentaZone.Indss.MatchingService.MatchingServiceReference.IMatchingService)(this)).EchoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IdentaZone.Indss.MatchingService.MatchingServiceReference.MatchResponse IdentaZone.Indss.MatchingService.MatchingServiceReference.IMatchingService.Match(IdentaZone.Indss.MatchingService.MatchingServiceReference.MatchRequest1 request) {
            return base.Channel.Match(request);
        }
        
        public string Match(IdentaZone.Indss.MatchingService.MatchingServiceReference.matchRequest matchRequest) {
            IdentaZone.Indss.MatchingService.MatchingServiceReference.MatchRequest1 inValue = new IdentaZone.Indss.MatchingService.MatchingServiceReference.MatchRequest1();
            inValue.matchRequest = matchRequest;
            IdentaZone.Indss.MatchingService.MatchingServiceReference.MatchResponse retVal = ((IdentaZone.Indss.MatchingService.MatchingServiceReference.IMatchingService)(this)).Match(inValue);
            return retVal.Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IdentaZone.Indss.MatchingService.MatchingServiceReference.MatchResponse> IdentaZone.Indss.MatchingService.MatchingServiceReference.IMatchingService.MatchAsync(IdentaZone.Indss.MatchingService.MatchingServiceReference.MatchRequest1 request) {
            return base.Channel.MatchAsync(request);
        }
        
        public System.Threading.Tasks.Task<IdentaZone.Indss.MatchingService.MatchingServiceReference.MatchResponse> MatchAsync(IdentaZone.Indss.MatchingService.MatchingServiceReference.matchRequest matchRequest) {
            IdentaZone.Indss.MatchingService.MatchingServiceReference.MatchRequest1 inValue = new IdentaZone.Indss.MatchingService.MatchingServiceReference.MatchRequest1();
            inValue.matchRequest = matchRequest;
            return ((IdentaZone.Indss.MatchingService.MatchingServiceReference.IMatchingService)(this)).MatchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IdentaZone.Indss.MatchingService.MatchingServiceReference.GetBspProvidersListResponse IdentaZone.Indss.MatchingService.MatchingServiceReference.IMatchingService.GetBspProvidersList(IdentaZone.Indss.MatchingService.MatchingServiceReference.GetBspProvidersListRequest request) {
            return base.Channel.GetBspProvidersList(request);
        }
        
        public string GetBspProvidersList(IdentaZone.Indss.MatchingService.MatchingServiceReference.Empty Empty) {
            IdentaZone.Indss.MatchingService.MatchingServiceReference.GetBspProvidersListRequest inValue = new IdentaZone.Indss.MatchingService.MatchingServiceReference.GetBspProvidersListRequest();
            inValue.Empty = Empty;
            IdentaZone.Indss.MatchingService.MatchingServiceReference.GetBspProvidersListResponse retVal = ((IdentaZone.Indss.MatchingService.MatchingServiceReference.IMatchingService)(this)).GetBspProvidersList(inValue);
            return retVal.Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IdentaZone.Indss.MatchingService.MatchingServiceReference.GetBspProvidersListResponse> IdentaZone.Indss.MatchingService.MatchingServiceReference.IMatchingService.GetBspProvidersListAsync(IdentaZone.Indss.MatchingService.MatchingServiceReference.GetBspProvidersListRequest request) {
            return base.Channel.GetBspProvidersListAsync(request);
        }
        
        public System.Threading.Tasks.Task<IdentaZone.Indss.MatchingService.MatchingServiceReference.GetBspProvidersListResponse> GetBspProvidersListAsync(IdentaZone.Indss.MatchingService.MatchingServiceReference.Empty Empty) {
            IdentaZone.Indss.MatchingService.MatchingServiceReference.GetBspProvidersListRequest inValue = new IdentaZone.Indss.MatchingService.MatchingServiceReference.GetBspProvidersListRequest();
            inValue.Empty = Empty;
            return ((IdentaZone.Indss.MatchingService.MatchingServiceReference.IMatchingService)(this)).GetBspProvidersListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IdentaZone.Indss.MatchingService.MatchingServiceReference.AddBspTemplateResponse IdentaZone.Indss.MatchingService.MatchingServiceReference.IMatchingService.AddBspTemplate(IdentaZone.Indss.MatchingService.MatchingServiceReference.AddBspTemplateRequest request) {
            return base.Channel.AddBspTemplate(request);
        }
        
        public string AddBspTemplate(IdentaZone.Indss.MatchingService.MatchingServiceReference.AddTemplateRequest AddTemplateRequest) {
            IdentaZone.Indss.MatchingService.MatchingServiceReference.AddBspTemplateRequest inValue = new IdentaZone.Indss.MatchingService.MatchingServiceReference.AddBspTemplateRequest();
            inValue.AddTemplateRequest = AddTemplateRequest;
            IdentaZone.Indss.MatchingService.MatchingServiceReference.AddBspTemplateResponse retVal = ((IdentaZone.Indss.MatchingService.MatchingServiceReference.IMatchingService)(this)).AddBspTemplate(inValue);
            return retVal.Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IdentaZone.Indss.MatchingService.MatchingServiceReference.AddBspTemplateResponse> IdentaZone.Indss.MatchingService.MatchingServiceReference.IMatchingService.AddBspTemplateAsync(IdentaZone.Indss.MatchingService.MatchingServiceReference.AddBspTemplateRequest request) {
            return base.Channel.AddBspTemplateAsync(request);
        }
        
        public System.Threading.Tasks.Task<IdentaZone.Indss.MatchingService.MatchingServiceReference.AddBspTemplateResponse> AddBspTemplateAsync(IdentaZone.Indss.MatchingService.MatchingServiceReference.AddTemplateRequest AddTemplateRequest) {
            IdentaZone.Indss.MatchingService.MatchingServiceReference.AddBspTemplateRequest inValue = new IdentaZone.Indss.MatchingService.MatchingServiceReference.AddBspTemplateRequest();
            inValue.AddTemplateRequest = AddTemplateRequest;
            return ((IdentaZone.Indss.MatchingService.MatchingServiceReference.IMatchingService)(this)).AddBspTemplateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IdentaZone.Indss.MatchingService.MatchingServiceReference.EnableUserResponse IdentaZone.Indss.MatchingService.MatchingServiceReference.IMatchingService.EnableUser(IdentaZone.Indss.MatchingService.MatchingServiceReference.EnableUserRequest1 request) {
            return base.Channel.EnableUser(request);
        }
        
        public string EnableUser(IdentaZone.Indss.MatchingService.MatchingServiceReference.enableUserRequest enableUserRequest) {
            IdentaZone.Indss.MatchingService.MatchingServiceReference.EnableUserRequest1 inValue = new IdentaZone.Indss.MatchingService.MatchingServiceReference.EnableUserRequest1();
            inValue.enableUserRequest = enableUserRequest;
            IdentaZone.Indss.MatchingService.MatchingServiceReference.EnableUserResponse retVal = ((IdentaZone.Indss.MatchingService.MatchingServiceReference.IMatchingService)(this)).EnableUser(inValue);
            return retVal.Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IdentaZone.Indss.MatchingService.MatchingServiceReference.EnableUserResponse> IdentaZone.Indss.MatchingService.MatchingServiceReference.IMatchingService.EnableUserAsync(IdentaZone.Indss.MatchingService.MatchingServiceReference.EnableUserRequest1 request) {
            return base.Channel.EnableUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<IdentaZone.Indss.MatchingService.MatchingServiceReference.EnableUserResponse> EnableUserAsync(IdentaZone.Indss.MatchingService.MatchingServiceReference.enableUserRequest enableUserRequest) {
            IdentaZone.Indss.MatchingService.MatchingServiceReference.EnableUserRequest1 inValue = new IdentaZone.Indss.MatchingService.MatchingServiceReference.EnableUserRequest1();
            inValue.enableUserRequest = enableUserRequest;
            return ((IdentaZone.Indss.MatchingService.MatchingServiceReference.IMatchingService)(this)).EnableUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IdentaZone.Indss.MatchingService.MatchingServiceReference.ConnectDBResponse IdentaZone.Indss.MatchingService.MatchingServiceReference.IMatchingService.ConnectDB(IdentaZone.Indss.MatchingService.MatchingServiceReference.ConnectDBRequest1 request) {
            return base.Channel.ConnectDB(request);
        }
        
        public string ConnectDB(IdentaZone.Indss.MatchingService.MatchingServiceReference.connectDBRequest connectDBRequest) {
            IdentaZone.Indss.MatchingService.MatchingServiceReference.ConnectDBRequest1 inValue = new IdentaZone.Indss.MatchingService.MatchingServiceReference.ConnectDBRequest1();
            inValue.connectDBRequest = connectDBRequest;
            IdentaZone.Indss.MatchingService.MatchingServiceReference.ConnectDBResponse retVal = ((IdentaZone.Indss.MatchingService.MatchingServiceReference.IMatchingService)(this)).ConnectDB(inValue);
            return retVal.Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IdentaZone.Indss.MatchingService.MatchingServiceReference.ConnectDBResponse> IdentaZone.Indss.MatchingService.MatchingServiceReference.IMatchingService.ConnectDBAsync(IdentaZone.Indss.MatchingService.MatchingServiceReference.ConnectDBRequest1 request) {
            return base.Channel.ConnectDBAsync(request);
        }
        
        public System.Threading.Tasks.Task<IdentaZone.Indss.MatchingService.MatchingServiceReference.ConnectDBResponse> ConnectDBAsync(IdentaZone.Indss.MatchingService.MatchingServiceReference.connectDBRequest connectDBRequest) {
            IdentaZone.Indss.MatchingService.MatchingServiceReference.ConnectDBRequest1 inValue = new IdentaZone.Indss.MatchingService.MatchingServiceReference.ConnectDBRequest1();
            inValue.connectDBRequest = connectDBRequest;
            return ((IdentaZone.Indss.MatchingService.MatchingServiceReference.IMatchingService)(this)).ConnectDBAsync(inValue);
        }
    }
}
